### PR TITLE
upgrade to node20

### PR DESCRIPTION
**Pull request by vctqs1**
**What**: Upgrade to node20

**Why**:
```
npm does not support Node.js v15.14.0. You should probably upgrade to a newer version of node 
```
The warning: https://github.com/OpenSourceRaidGuild/babel-vite/actions/runs/7214403907/job/19656427159#step:5:434

After upgrade to node20: No warning anymore https://github.com/vctqs1/babel-vite/actions/runs/7231706878/job/19705165603#step:5:28

https://github.com/OpenSourceRaidGuild/babel-vite/actions/runs/7214403907/job/19656533364#step:7:168)

**How**: Install node20 in CI

**Checklist**:

- [x] Documentation updated
- [x] Tests
- [x] Ready to be merged
      
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by vctqs1** [comment]
@JacobMGEvans @mpeyper Could you two help to review this PR

**Review by mpeyper — APPROVED** [review]
Thanks!

**Comment by mpeyper** [comment]
Still [failing to release](https://github.com/OpenSourceRaidGuild/babel-vite/actions/runs/7244477736/job/19732886850) 😞

**Comment by vctqs1** [comment]
seem another error 
```

npm ERR! code ETARGET
npm ERR! notarget No matching version found for babel-plugin-transform-vite-meta-glob@1.1.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

the latest version is 1.0.3 https://www.npmjs.com/package/babel-plugin-transform-vite-meta-glob
image

**Comment by vctqs1** [comment]
Seem The problem arises because the release for `babel-preset-vite` is attempting to use version `1.1.0` of `babel-plugin-transform-vite-meta-glob`, but it seems that version hasn't been released yet due to a change in the release order.

https://github.com/OpenSourceRaidGuild/babel-vite/actions/runs/7244477736/job/19732886850#step:7:97

The correct sequence should have been releasing `babel-plugin-transform-vite-meta-glob` version `1.1.0` first, followed by the release of `babel-preset-vite` version `1.1.1`. However, it seems that the order got mixed up, causing `babel-preset-vite` to look for a version of `babel-plugin-transform-vite-meta-glob` that hasn't been released yet.


@mpeyper The release order is randomly or specific order?

**Comment by vctqs1** [comment]
@mpeyper I created another PR https://github.com/OpenSourceRaidGuild/babel-vite/pull/47 to set `--sequential-init` avoid hypothetical concurrent initialization collisions.
(https://www.npmjs.com/package/@qiwi/multi-semantic-release)

**Pull request merged**
