### PR TITLE
Adding `--sequential-init` to avoid hypothetical concurrent initialization collisions.

### PR DESCRIPTION
**Pull request by vctqs1**
**What**:

sequentialInit | boolean | --sequential-init | Avoid hypothetical concurrent initialization collisions.
-- | -- | -- | --
sequentialPrepare | boolean | --sequential-prepare | Avoid hypothetical concurrent preparation collisions. True by default

**Why**:

[
](https://github.com/OpenSourceRaidGuild/babel-vite/pull/46#issuecomment-1859662420)

**Checklist**:

- [x] Documentation updated
- [x] Tests
- [x] Ready to be merged
      
- [x] Added myself to contributors table

### CODE REVIEW

**Review by mpeyper — APPROVED** [review]
Let’s give it a shot

**Comment by vctqs1** [comment]
Still getting failure https://github.com/OpenSourceRaidGuild/babel-vite/actions/runs/7245459470/job/19735564466#step:7:106

**Comment by vctqs1** [comment]
I've no clue, what should we do now, do you have any suggestion? @mpeyper

**Comment by vctqs1** [comment]
ah wait, it said no new version create 
```
[8:29:58 AM] [babel-plugin-transform-vite-meta-glob] › ℹ  The next release version is 1.1.0
[8:29:58 AM] [babel-plugin-transform-vite-meta-glob] › ℹ  Start step "generateNotes" of plugin "Inline plugin"
[8:29:58 AM] [babel-plugin-transform-vite-meta-hot] › ℹ  There are no relevant changes, so no new version is released.
```
but not sure why version still bump to 1.1.0 if no relevant changes?

**Comment by mpeyper** [comment]
Unfortunately not. Last time I did any work on this it just worked so I'm a bit confused as to how to fix this. 

I'll raise an issue with `multi-semantic-release` asking for some help, but not sure what kind of turn around time that might have.

**Comment by vctqs1** [comment]
okay thank you

**Comment by mpeyper** [comment]
FYI @vctqs1 - #48, #49

**Comment by mpeyper** [comment]
Looks like #49 fixed it @vctqs1

**Comment by vctqs1** [comment]
thank you so much

**Pull request merged**
